Operations sur les matrices

In [1]:
import numpy as np

In [11]:
X=np.array([[1,2],[3,4],[5,6]], dtype=np.int16)

In [12]:
X

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int16)

In [13]:
X.ndim

2

In [14]:
X.shape

(3, 2)

In [15]:
X.dtype

dtype('int16')

Indexation & Slicing

In [16]:
# premiere ligne premiere colonne
X[0,0]

1

In [17]:
#derniere ligne, derniere colonne
X[-1,-1]

6

In [18]:
# les deux dernières lignes
X[[-2,-1],:]

array([[3, 4],
       [5, 6]], dtype=int16)

In [19]:
# les deux dernières lignes
X[-2:,:]

array([[3, 4],
       [5, 6]], dtype=int16)

In [20]:
# matrice avec ordre inversé de lignes 
X[::-1,:]

array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int16)

Opérateurs des matrices

In [21]:
X=np.array([[1,2],[3,4],[5,6]], dtype=np.int16)
Y=np.array([[1,1],[1,1],[1,1]], dtype=np.int16)

In [22]:
Z=X+Y
Z

array([[2, 3],
       [4, 5],
       [6, 7]], dtype=int16)

In [23]:
# Matrice avec des 1
Y=np.ones(shape=(3,2), dtype=np.int16)
Y

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int16)

In [24]:
# Matrice avec des 0
Y1=np.zeros(shape=(3,2), dtype=np.int16)
Y1

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int16)

Remarque:
- Math. parlant, `X*Y` n'est pas valide !
- De pt de vue Numpy, il s'agit d'une astuce

In [26]:
X

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int16)

In [27]:
Y

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int16)

In [25]:
X*Y

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int16)

produit matriciel

In [29]:
X=np.array([[1,2],[3,4],[5,6]])
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
Y=np.array([[1,1,1,1,1,1],[2,2,2,2,2,2]])
Y

array([[1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2]])

In [31]:
np.dot(X,Y)

array([[ 5,  5,  5,  5,  5,  5],
       [11, 11, 11, 11, 11, 11],
       [17, 17, 17, 17, 17, 17]])

Operateurs entre matrices et scalaires

In [34]:
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
X+1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [35]:
X.shape[0] # nb de lignes de X

3

In [36]:
X.shape[1] # nb de colonnes de X

2

In [37]:
Z=np.empty(shape=X.shape, dtype=X.dtype)
for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        Z[i,j]=X[i,j]+1
Z

array([[2, 3],
       [4, 5],
       [6, 7]])

Operations entre matrices et vecteurs

In [39]:
x=np.array([2,3])
x

array([2, 2])

In [40]:
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
X+x

array([[3, 4],
       [5, 6],
       [7, 8]])

Fonctions sur les matrices

La somme

In [43]:
X.sum()

21

In [44]:
X.sum(axis=0)

array([ 9, 12])

In [45]:
X.sum(axis=1)

array([ 3,  7, 11])

In [46]:
np.sum(X)

21

In [47]:
np.sum(X, axis=0)

array([ 9, 12])

<b>Exercice:</b>

- Soit un employé qui s'appelle `Ines` dont les infos sont `age=28, salaire=1500`
- Soit un ensemble des employés dont les infos :

        Ali : age=30, salaire=2500
        Sonia: age=35, salaire=1100
        Rahma: age=25, salaire=900

Quel est le nom de l'employé le plus proche à `Ines` ?

In [48]:
ines=np.array([28,1500])

In [49]:
noms=['Ali','Sonia','Rahma']

In [50]:
employes=np.array([[30,2500],
                   [35,1100],
                   [25,900]])

In [64]:
distances=[]
for i in range(employes.shape[0]):
    d=np.sqrt(np.sum((employes[i]-ines)**2))
    distances.append(d)

In [66]:
distances=np.array(distances)
distances

array([1000.002     ,  400.06124531,  600.00749995])

In [68]:
indice_dist_min=distances.argmin()
indice_dist_min

1

In [70]:
print('L\'employé le plus proche de Ines est',noms[indice_dist_min])

L'employé le plus proche de Ines est Sonia


In [76]:
noms[np.argmin(np.sqrt(np.sum((employes-ines)**2, axis=1)))]

'Sonia'