Les objectifs :
- Gestion des exceptions
- Manipulation des objets math avec Numpy

<b>Gestion des exceptions</b>

In [4]:
x=float(input('Entrer un réel'))
y=float(input('Entrer un réel'))
z=x/y
print(z)

ValueError: could not convert string to float: 'hello'

In [6]:
try:
    x=float(input('Entrer un réel'))
    y=float(input('Entrer un réel'))
    z=x/y
    print(z)
except:
    print('Erreur !!!!')

Erreur !!!!


In [8]:
try:
    x=float(input('Entrer un réel'))
    y=float(input('Entrer un réel'))
    z=x/y
    print(z)
except ValueError:
    print('Erreur : SVP veuillez saisir un réel !!!!')

ZeroDivisionError: float division by zero

In [10]:
try:
    x=float(input('Entrer un réel'))
    y=float(input('Entrer un réel'))
    z=x/y
    print(z)
except ValueError:
    print('Erreur : SVP veuillez saisir un réel !!!!')
except ZeroDivisionError:
    print('Erreur : SVP veuillez saisir un réel diffréent de 0 comme 2eme entrée !!!!')

Erreur : SVP veuillez saisir un réel diffréent de 0 comme 2eme entrée !!!!


In [12]:
try:
    x=float(input('Entrer un réel'))
    y=float(input('Entrer un réel'))
    z=x/y
    print(z)
except ValueError:
    print('Erreur : SVP veuillez saisir un réel !!!!')
except ZeroDivisionError:
    print('Erreur : SVP veuillez saisir un réel diffréent de 0 comme 2eme entrée !!!!')
finally:
    print('Fin de l\'opération')

5.0
Fin de l'opération


<b>Manipulation des objets math. avec Numpy</b>

Mnaipulation des scalaires

Avec numpy, on utilise la fonction `np.array()` pour créer des objets math.

Dans le cas des objets scalaires, il est suffisant de travailler avec Python tout court.

In [14]:
import numpy as np

In [15]:
x=np.array(1)
y=np.array(2)
z=x+y

In [16]:
z

3

In [17]:
x=1
y=2
z=x+y

In [18]:
z

3

Manipulation des vecteurs

In [19]:
x=np.array([1,2])
y=np.array([1,1])
z=x+y
z

array([2, 3])

In [20]:
x=[1,2]
y=[1,1]
z=x+y
z

[1, 2, 1, 1]

Manipulation des matrices

In [21]:
x=np.array([[1,2],[3,4]])
y=np.array([[1,1],[1,1]])
z=x+y
z

array([[2, 3],
       [4, 5]])

In [22]:
x=[[1,2],[3,4]]
y=[[1,1],[1,1]]
z=x+y
z

[[1, 2], [3, 4], [1, 1], [1, 1]]

Proprités des objets math.

In [23]:
x=np.array([1,2])

In [24]:
x.ndim # pour vérifier qu'il s'agit d'un vecteur , càd ndim=1

1

In [25]:
x.shape # taille de la dimension de vecteur , dans notre cas = 2

(2,)

In [26]:
x.dtype

dtype('int32')

In [27]:
x

array([1, 2])

In [28]:
x=np.array([1,2] , dtype=np.uint8)

In [29]:
x

array([1, 2], dtype=uint8)

In [32]:
x+300

array([301, 302], dtype=uint16)

In [33]:
x=np.array([[1,2],[3,4],[5,6]])

In [34]:
x.ndim

2

In [35]:
x.shape

(3, 2)

In [36]:
x.shape[0] # nb de lignes

3

In [38]:
x.shape[1] # nb de colonnes

2

<b>Opérations sur les objets math.</b>

Opérations math. entre vecteurs

In [39]:
x1=np.array([1,2])
x2=np.array([1,1])

In [40]:
x1+x2 # op math

array([2, 3])

In [41]:
x1-x2 # op math

array([0, 1])

In [42]:
x1*x2 # alg

array([1, 2])

In [44]:
x=[] # resultat
for i in range(len(x1)):
    x.append(x1[i]*x2[i])
np.array(x)

array([1, 2])

Remarque:

Pour calculer le `produit scalaire` de deux vecteurs, on utilise la fonction `np.dot(vec1, vec2)`

In [45]:
np.dot(x1,x2) # produit scalaire

3

In [64]:
ages = np.array([31,40,15,55,27]) # vecteur qui contient l'age des personnes

On peut calculer l'age de la personne la plus agée

On utilise la fonction `np.max()`

In [47]:
ages.max()

55

In [48]:
np.max(ages)

55

In [49]:
ages.min()

15

In [50]:
ages.mean() # calculer la moyenne d'ages

33.6

In [51]:
ages.var()

179.04

In [52]:
ages1 = np.array([31,29,30,34,26])
ages2 = np.array([5,55,30,15,45])

In [53]:
ages1.mean()

30.0

In [54]:
ages2.mean()

30.0

In [56]:
ages1.var()

6.8

In [57]:
ages2.var()

340.0

In [59]:
ages

array([31, 40, 15, 55, 27])

In [60]:
ages.min()

15

In [58]:
ages.argmin() # position de la valeur min

2

In [61]:
ages.argmax()# position de la valeur max

3

In [62]:
ages.sort()

In [63]:
ages

array([15, 27, 31, 40, 55])

In [65]:
np.sort(ages)

array([15, 27, 31, 40, 55])

In [66]:
ages

array([31, 40, 15, 55, 27])

In [67]:
np.argsort(ages)

array([2, 4, 0, 1, 3], dtype=int64)

Indexation & Slicing

In [68]:
ages[0]  # on utilise les indices pour acceder aux elements (exactement comme les listes) 

31

In [69]:
ages[:3]

array([31, 40, 15])

In [70]:
ages[-3:] # retourne un vecteur qui contient les 3 derniers elements

array([15, 55, 27])

In [71]:
ages

array([31, 40, 15, 55, 27])